// <auto-generated />
using System;
using LAB5.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAB5.Migrations
{
    [DbContext(typeof(FoodShippingContext))]
    partial class FoodShippingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LAB5.Models.Account", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Makh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("LAB5.Models.Cthd", b =>
                {
                    b.Property<string>("Mahd")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sl")
                        .HasColumnType("int");

                    b.HasKey("Mahd");

                    b.ToTable("Cthds");
                });

            modelBuilder.Entity("LAB5.Models.Hoadon", b =>
                {
                    b.Property<string>("Mahd")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Makh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngayhd")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Tht")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Mahd");

                    b.ToTable("Hoadons");
                });

            modelBuilder.Entity("LAB5.Models.Khachhang", b =>
                {
                    b.Property<string>("Makh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Makh");

                    b.ToTable("Khachhangs");
                });

            modelBuilder.Entity("LAB5.Models.Monan", b =>
                {
                    b.Property<string>("Mama")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Dongia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Loaima")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mama");

                    b.ToTable("Monans");
                });
#pragma warning restore 612, 618
        }
    }
}
